url: ""
# baseurl: "/cultural-economics"
baseurl: ""
title: "Cultural Economics"
logo: "Cult/Econ"
desc: "A repository of guides and coursesto reskill communities with traditional skills and crafts, and power a cultural economy."

collections:
  guides:
    output: true
  skills:
    output: true