url: "" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "/cultural-economics" # the subpath of your site, e.g. /blog
baseurl: ""
title: "Cultural Economics" # the name of your site, e.g. ACME Corp.
logo: "Cult/Econ"
desc: "A repository of guides and coursesto reskill communities with traditional skills and crafts, and power a cultural economy."

collections:
  guides:
    output: true
  skills:
    output: true

destination: docs/